
train: C:\Users\gamer\Downloads\testing.v4i.yolov8/train/images
val: C:\Users\gamer\Downloads\testing.v4i.yolov8/valid/images
test: C:\Users\gamer\Downloads\testing.v4i.yolov8/test/images

nc: 4
names: ['People', 'ceiling', 'floor', 'wall']